# Generated by Django 4.1.3 on 2022-11-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=16, verbose_name='id')),
                ('party1', models.CharField(max_length=16, verbose_name='A')),
                ('party2', models.CharField(max_length=16, verbose_name='B')),
                ('prod_class', models.CharField(max_length=16)),
                ('prod_type', models.CharField(max_length=16)),
                ('trade_dt', models.DateField(verbose_name='Trade Date')),
                ('input_dt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
