# Generated by Django 4.1.3 on 2022-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=20)),
                ('f_data', models.FileField(null=True, upload_to='documents')),
                ('upload_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
